  node{

        stage('Build'){
            println("running build stage")

        }
        stage('Test'){

                println("running test stage")
        }
        stage('Deploy'){

                println("running deploy stage")
        }

    }